# Generated by Django 6.0.7 on 2026-07-24 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Dialyse Maschinen', 'Dialyse Maschinen'), ('Dialyse Betten', 'Dialyse Betten'), ('Andere Geräte', 'Andere Geräte')], max_length=100, verbose_name='Geräteart')),
                ('name', models.CharField(max_length=200, verbose_name='Gerätbezeichnung')),
                ('inventory_number', models.CharField(max_length=100, unique=True, verbose_name='Inventarnummer')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Seriennummer')),
                ('ec_number', models.CharField(blank=True, max_length=100, verbose_name='EC-Nummer')),
                ('software_version', models.CharField(blank=True, max_length=100, verbose_name='Software Version')),
                ('operating_hours', models.IntegerField(blank=True, null=True, verbose_name='Betriebsstunden')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Hersteller')),
                ('year_built', models.IntegerField(blank=True, null=True, verbose_name='Baujahr')),
                ('area', models.CharField(choices=[('Dialyse', 'Dialyse'), ('Praxis', 'Praxis'), ('Labor', 'Labor')], max_length=30, verbose_name='Bereich')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='Raum')),
                ('last_stk', models.DateField(blank=True, null=True, verbose_name='Letzte STK')),
                ('next_stk', models.DateField(blank=True, null=True, verbose_name='Nächste STK')),
                ('last_mtk', models.DateField(blank=True, null=True, verbose_name='Letzte MTK')),
                ('next_mtk', models.DateField(blank=True, null=True, verbose_name='Nächste MTK')),
                ('last_dguv', models.DateField(blank=True, null=True, verbose_name='Letzte DGUV V3')),
                ('next_dguv', models.DateField(blank=True, null=True, verbose_name='Nächste DGUV V3')),
                ('status', models.CharField(choices=[('Aktiv', 'Aktiv'), ('Nicht aktiv', 'Nicht aktiv')], default='Aktiv', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('image', models.ImageField(blank=True, null=True, upload_to='devices/')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='general_documents/')),
                ('category', models.CharField(choices=[('Zertifikat', '📜 Techniker Zertifikate'), ('Sonstiges', '📄 Sonstige Dokumente')], max_length=50)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='home_slider/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='home_slider/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='home_slider/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='home_slider/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='home_slider/')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_name', models.CharField(blank=True, max_length=200, verbose_name='Praxisname')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail-Adresse')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefonnummer')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
                ('contact_image', models.ImageField(blank=True, null=True, upload_to='practice_contact/', verbose_name='Kontaktbild')),
            ],
        ),
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Bedienungsanleitung', '📘 Bedienungsanleitung'), ('Erstinbetriebnahme', '🚀 Erstinbetriebnahme'), ('Wiederinbetriebnahme', '🔄 Wiederinbetriebnahme'), ('STK-Protokolle', '🩺 STK-Protokolle'), ('MTK-Protokolle', '❤️ MTK-Protokolle'), ('DGUV-Protokolle', '⚡ DGUV-Protokolle'), ('STK-Berichte', '📄 STK-Berichte'), ('MTK-Berichte', '📄 MTK-Berichte'), ('DGUV-Berichte', '📄 DGUV-Berichte'), ('Einweisungsnachweise', '📋 Einweisungsnachweise')], max_length=50, verbose_name='Dokumenttyp')),
                ('file', models.FileField(upload_to='device_documents/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='Anzeigename')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='Reparatur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(auto_now_add=True)),
                ('beschreibung', models.TextField(verbose_name='Problem Beschreibung')),
                ('melder', models.CharField(blank=True, max_length=100, verbose_name='Melder')),
                ('techniker', models.CharField(blank=True, max_length=100, verbose_name='Techniker')),
                ('status', models.CharField(choices=[('Offen', 'Offen'), ('In Bearbeitung', 'In Bearbeitung'), ('Erledigt', 'Erledigt')], default='Offen', max_length=50, verbose_name='Status')),
                ('ausfuehrung', models.TextField(blank=True, verbose_name='Ausführung')),
                ('reparatur_datum', models.DateField(blank=True, null=True, verbose_name='Reparaturdatum')),
                ('reparaturbericht', models.FileField(blank=True, null=True, upload_to='reparaturberichte/')),
                ('reparaturbild', models.ImageField(blank=True, null=True, upload_to='reparaturbild/')),
                ('geraet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparaturen', to='devices.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.standort', verbose_name='Standort'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('contact_image', models.ImageField(blank=True, null=True, upload_to='contact_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
