# Generated by Django 6.0.7 on 2026-07-25 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedocument',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='practicesettings',
            name='practice_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Standort'),
        ),
        migrations.CreateModel(
            name='Filterwechsel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('filtercode', models.CharField(max_length=100)),
                ('anzahl', models.PositiveIntegerField(default=1)),
                ('durchgefuehrt_von', models.CharField(max_length=150)),
                ('bemerkung', models.TextField(blank=True)),
                ('dokument1', models.FileField(blank=True, null=True, upload_to='filterwechsel/')),
                ('dokument2', models.FileField(blank=True, null=True, upload_to='filterwechsel/')),
                ('geraet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filterwechsel', to='devices.device')),
            ],
        ),
    ]
