# Generated by Django 6.0.7 on 2026-07-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_devicedocument_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterwechsel',
            name='dokument1',
        ),
        migrations.RemoveField(
            model_name='filterwechsel',
            name='dokument2',
        ),
    ]
