# Generated by Django 6.0.7 on 2026-07-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_filterwechsel_dokument1_and_more'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='filterwechsel',
            name='anzahl',
        ),

        migrations.RemoveField(
            model_name='filterwechsel',
            name='durchgefuehrt_von',
        ),

        migrations.RemoveField(
            model_name='filterwechsel',
            name='geraet',
        ),

        migrations.AddField(
            model_name='filterwechsel',
            name='anzahl_filter',
            field=models.IntegerField(default=1),
        ),

        migrations.AddField(
            model_name='filterwechsel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),

        migrations.AddField(
            model_name='filterwechsel',
            name='durchgeführt_von',
            field=models.CharField(
                default='Unbekannt',
                max_length=100
            ),
        ),

        migrations.AddField(
            model_name='filterwechsel',
            name='inventarnummer',
            field=models.CharField(
                default='Unbekannt',
                max_length=100
            ),
        ),
    ]