# Generated by Django 6.0.7 on 2026-07-25 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_remove_filterwechsel_anzahl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterwechsel',
            name='geraet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filterwechsel', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='filterwechsel',
            name='anzahl_filter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='filterwechsel',
            name='durchgeführt_von',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='filterwechsel',
            name='inventarnummer',
            field=models.CharField(max_length=100),
        ),
    ]
