# Generated by Django 6.0.7 on 2026-07-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_filterwechsel_geraet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geraetart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
