# Generated by Django 6.0.7 on 2026-07-26 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_geraeteart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='category',
        ),
        migrations.AddField(
            model_name='device',
            name='geraetart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geraete', to='devices.geraetart'),
        ),
        migrations.AddField(
            model_name='geraetart',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
    ]
