# Generated by Django 6.0.7 on 2026-07-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_remove_device_category_device_geraetart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('document_type', models.CharField(choices=[('Arbeitsanweisung', '📋 Arbeitsanweisung'), ('SOP', '📘 SOP'), ('Checkliste', '✅ Checkliste'), ('Formular', '📄 Formular'), ('Schulung', '🎓 Schulung'), ('QM-Dokument', '📑 QM-Dokument'), ('Sonstiges', '📁 Sonstiges')], max_length=50, verbose_name='Dokumenttyp')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='technician_documents/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
            ],
        ),
    ]
