# Generated by Django 6.0.7 on 2026-07-27 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_techniciandocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniciandocument',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='techniciandocument',
            name='document_type',
        ),
        migrations.AddField(
            model_name='techniciandocument',
            name='category',
            field=models.CharField(choices=[('Zertifikat', '📜 Zertifikat'), ('Servicehandbuch', '📘 Servicehandbuch'), ('Bedienungsanleitung', '📖 Bedienungsanleitung'), ('Software', '💻 Software'), ('Schulung', '🎓 Schulung'), ('Sonstiges', '📄 Sonstiges')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techniciandocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='techniciandocument',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='techniciandocument',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Dokumentname'),
        ),
    ]
