# Generated by Django 6.0.7 on 2026-07-27 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_documenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.documenttype', verbose_name='Dokumenttyp'),
        ),
    ]
