# Generated by Django 6.0.7 on 2026-07-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_alter_devicedocument_document_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='documenttype',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Reihenfolge'),
        ),
    ]
