# Generated by Django 6.0.7 on 2026-07-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_alter_documenttype_options_documenttype_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_luebeck', models.BooleanField(default=True, verbose_name='Gesamtgeräte Lübeck anzeigen')),
                ('show_ratzeburg', models.BooleanField(default=True, verbose_name='Gesamtgeräte Ratzeburg anzeigen')),
                ('show_reparaturen', models.BooleanField(default=True, verbose_name='Reparaturen anzeigen')),
                ('show_stk', models.BooleanField(default=True, verbose_name='STK anzeigen')),
                ('show_mtk', models.BooleanField(default=True, verbose_name='MTK anzeigen')),
                ('show_dguv', models.BooleanField(default=True, verbose_name='DGUV anzeigen')),
                ('show_geraete_uebersicht', models.BooleanField(default=True, verbose_name='Geräteübersicht anzeigen')),
            ],
        ),
    ]
