# Generated by Django 6.0.7 on 2026-07-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_companyinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='ansprechpartner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
