# Generated by Django 6.0.7 on 2026-07-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_contactinformation_homeinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinformation',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact/'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='technician_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
