# Generated by Django 6.0.7 on 2026-07-28 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_remove_contactinformation_contact_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contact/gallery/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='devices.contactinformation')),
            ],
        ),
    ]
