# Generated by Django 6.0.7 on 2026-07-28 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_contactimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeinformation',
            name='text',
        ),
        migrations.AlterField(
            model_name='homeinformation',
            name='title',
            field=models.CharField(default='Willkommen im Medizintechnik Management System', max_length=200),
        ),
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/gallery/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='devices.homeinformation')),
            ],
        ),
    ]
