# Generated by Django 6.0.7 on 2026-07-29 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_remove_homeinformation_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('devices_overview', 'Geräteübersicht'), ('devices', 'Geräte'), ('repairs_open', 'Offene Reparaturen'), ('repairs_progress', 'Reparaturen in Bearbeitung'), ('repair_history', 'Reparaturhistorie'), ('filter_history', 'Filterwechselhistorie'), ('stk', 'STK fällig'), ('mtk', 'MTK fällig'), ('dguv', 'DGUV fällig'), ('device_documents', 'Medizinische Geräte Dokumente'), ('technician_documents', 'Techniker Dokumente')], max_length=50)),
                ('visible', models.BooleanField(default=True, verbose_name='Im Dashboard anzeigen')),
                ('order', models.PositiveIntegerField(default=0)),
                ('geraetart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.geraetart')),
                ('standort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.standort')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
