# Generated by Django 6.0.7 on 2026-07-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_dashboardwidget'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='color',
            field=models.CharField(choices=[('primary', '🔵 Blau'), ('success', '🟢 Grün'), ('danger', '🔴 Rot'), ('warning', '🟡 Gelb'), ('info', '🔷 Türkis'), ('purple', '🟣 Lila'), ('dark', '⚫ Schwarz')], default='primary', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='icon',
            field=models.CharField(choices=[('bi-grid', '🧩 Allgemein'), ('bi-hospital', '🏥 Krankenhaus'), ('bi-heart-pulse', '❤️ Medizintechnik'), ('bi-tools', '🛠 Reparatur'), ('bi-wrench', '🔧 Wartung'), ('bi-file-earmark-text', '📄 Dokument'), ('bi-folder', '📁 Ordner'), ('bi-building', '🏢 Firma'), ('bi-gear', '⚙ Einstellungen'), ('bi-lightning-charge', '⚡ DGUV'), ('bi-calendar-check', '📅 Termin')], default='bi-grid', max_length=50),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Eigener Titel'),
        ),
    ]
