# Generated by Django 6.0.7 on 2026-07-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0022_dashboardwidget_color_dashboardwidget_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='icon',
            field=models.CharField(choices=[('bi-grid', '📊 Übersicht'), ('bi-hospital', '🏥 Krankenhaus'), ('bi-heart-pulse', '❤️ Medizin'), ('bi-tools', '🛠 Reparaturen'), ('bi-wrench', '🔧 Wartung'), ('bi-filter', '🧪 Filterwechsel'), ('bi-file-earmark-text', '📄 Dokumente'), ('bi-building', '🏢 Firma'), ('bi-folder', '📁 Ordner'), ('bi-gear', '⚙ Einstellungen')], default='bi-grid', max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(choices=[('devices_overview', 'Geräteübersicht'), ('devices', 'Geräte'), ('repairs_open', 'Offene Reparaturen'), ('repairs_progress', 'Reparaturen in Bearbeitung'), ('repairs_done', 'Reparaturen erledigt'), ('repair_history', 'Reparaturhistorie'), ('filter_history', 'Filterwechselhistorie'), ('stk', 'STK fällig'), ('mtk', 'MTK fällig'), ('dguv', 'DGUV fällig'), ('device_documents', 'Medizingeräte Dokumente'), ('technician_documents', 'Technikerdokumente')], max_length=50),
        ),
    ]
