# Generated by Django 6.0.7 on 2026-07-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_alter_dashboardwidget_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='color',
            field=models.CharField(choices=[('primary', '🔵 Blau'), ('success', '🟢 Grün'), ('danger', '🔴 Rot'), ('warning', '🟡 Gelb'), ('info', '🔷 Türkis'), ('purple', '🟣 Lila'), ('dark', '⚫ Schwarz'), ('orange', '🟠 Orange'), ('teal', '🟦 Petrol'), ('pink', '🩷 Pink'), ('brown', '🟤 Braun'), ('gray', '⚪ Grau')], default='primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='homeinformation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
