# Generated by Django 6.0.7 on 2026-07-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0024_alter_dashboardwidget_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Version')),
                ('release_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, verbose_name='Update Notes')),
                ('installed', models.BooleanField(default=False)),
            ],
        ),
    ]
