# Generated by Django 6.0.7 on 2026-08-05 06:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0025_systemupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='systemupdate',
            name='installed',
        ),
        migrations.RemoveField(
            model_name='systemupdate',
            name='release_date',
        ),
        migrations.AddField(
            model_name='systemupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemupdate',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systemupdate',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemupdate',
            name='local_commit',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='systemupdate',
            name='remote_commit',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='systemupdate',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemupdate',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemupdate',
            name='status',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='IDLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemupdate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='systemupdate',
            name='version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
