# Generated by Django 6.0.7 on 2026-08-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0026_alter_systemupdate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geraetart',
            name='braucht_pruefung',
            field=models.BooleanField(default=True, verbose_name='Benötigt STK / MTK / DGUV'),
        ),
    ]
