# Generated by Django 6.0.7 on 2026-08-10 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0027_geraetart_braucht_pruefung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pruefart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Prüfart')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('intervall_jahre', models.PositiveIntegerField(choices=[(1, 'Jährlich'), (2, 'Alle 2 Jahre'), (3, 'Alle 3 Jahre'), (4, 'Alle 4 Jahre'), (5, 'Alle 5 Jahre'), (0, 'Kein Intervall')], default=1, verbose_name='Prüfintervall')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Prüfart',
                'verbose_name_plural': 'Prüfarten',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='geraetart',
            name='braucht_pruefung',
        ),
        migrations.CreateModel(
            name='DevicePruefung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letztes_datum', models.DateField(blank=True, null=True, verbose_name='Letzte Prüfung')),
                ('naechstes_datum', models.DateField(blank=True, null=True, verbose_name='Nächste Prüfung')),
                ('bemerkung', models.TextField(blank=True, verbose_name='Bemerkung')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruefungen', to='devices.device')),
                ('pruefart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geraete_pruefungen', to='devices.pruefart')),
            ],
            options={
                'verbose_name': 'Geräteprüfung',
                'verbose_name_plural': 'Geräteprüfungen',
                'ordering': ['pruefart__order', 'pruefart__name'],
                'constraints': [models.UniqueConstraint(fields=('device', 'pruefart'), name='unique_device_pruefart')],
            },
        ),
    ]
