# Generated by Django 6.0.7 on 2026-08-12 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_pruefart_remove_geraetart_braucht_pruefung_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDetailFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('geraetart', 'Gerätart'), ('geraetbeschreibung', 'Gerätbeschreibung'), ('inventarnummer', 'Inventarnummer'), ('seriennummer', 'Seriennummer'), ('softwareversion', 'Softwareversion'), ('betriebsstunden', 'Betriebsstunden'), ('hersteller', 'Hersteller'), ('baujahr', 'Baujahr'), ('standort', 'Standort'), ('bereich', 'Bereich'), ('pruefart', 'Prüfart'), ('raum', 'Raum'), ('status', 'Status')], max_length=100)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('geraetart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_field_configs', to='devices.geraetart')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('geraetart', 'field_name')},
            },
        ),
    ]
