# Generated by Django 6.0.7 on 2026-08-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0029_devicedetailfieldconfig'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devicedetailfieldconfig',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='devicedetailfieldconfig',
            name='field_name',
            field=models.CharField(choices=[('geraetart', 'Gerätart'), ('name', 'Gerätbezeichnung'), ('inventory_number', 'Inventarnummer'), ('serial_number', 'Seriennummer'), ('ec_number', 'EC-Nummer'), ('software_version', 'Software Version'), ('operating_hours', 'Betriebsstunden'), ('manufacturer', 'Hersteller'), ('year_built', 'Baujahr'), ('practice', 'Standort'), ('area', 'Bereich'), ('room', 'Raum'), ('status', 'Status'), ('notes', 'Bemerkungen')], max_length=100),
        ),
        migrations.AddConstraint(
            model_name='devicedetailfieldconfig',
            constraint=models.UniqueConstraint(fields=('geraetart', 'field_name'), name='unique_geraetart_detail_field'),
        ),
    ]
