# Generated by Django 6.0.7 on 2026-08-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0030_alter_devicedetailfieldconfig_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedetailfieldconfig',
            name='field_name',
            field=models.CharField(choices=[('geraetart', 'Gerätart'), ('name', 'Gerätbezeichnung'), ('inventory_number', 'Inventarnummer'), ('serial_number', 'Seriennummer'), ('ec_number', 'EC-Nummer'), ('software_version', 'Software Version'), ('operating_hours', 'Betriebsstunden'), ('manufacturer', 'Hersteller'), ('year_built', 'Baujahr'), ('practice', 'Standort'), ('area', 'Bereich'), ('pruefart', 'Prüfart'), ('room', 'Raum'), ('status', 'Status'), ('notes', 'Bemerkungen')], max_length=100),
        ),
    ]
