# Generated by Django 6.0.7 on 2026-08-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0031_alter_devicedetailfieldconfig_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniciandocument',
            name='category',
            field=models.CharField(choices=[('Schulungszertifikate', '🎓 Schulungszertifikate'), ('Wartungsprotokolle', '🔧 Wartungsprotokolle'), ('Serviceberichte', '🛠️ Serviceberichte'), ('Sonstige Dokumente', '📄 Sonstige Dokumente')], max_length=100, verbose_name='Dokumentart'),
        ),
    ]
