# Generated by Django 6.0.7 on 2026-08-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0032_alter_techniciandocument_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparatur',
            name='techniker_gelesen',
            field=models.BooleanField(default=False),
        ),
    ]
