# Generated by Django 6.0.7 on 2026-08-19 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0033_reparatur_techniker_gelesen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rechnungsnummer', models.CharField(max_length=100, verbose_name='Rechnungsnummer')),
                ('rechnungsdatum', models.DateField(verbose_name='Rechnungsdatum')),
                ('lieferant', models.CharField(max_length=200, verbose_name='Lieferant / Firma')),
                ('auftragsnummer', models.CharField(blank=True, max_length=100, verbose_name='Auftragsnummer')),
                ('lieferscheinnummer', models.CharField(blank=True, max_length=100, verbose_name='Lieferscheinnummer')),
                ('kundennummer', models.CharField(blank=True, max_length=100, verbose_name='Kundennummer')),
                ('leistungsdatum', models.DateField(blank=True, null=True, verbose_name='Leistungsdatum')),
                ('rechnungsbetrag', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Rechnungsbetrag')),
                ('zahlungsziel', models.PositiveIntegerField(blank=True, null=True, verbose_name='Zahlungsziel (Tage)')),
                ('faelligkeitsdatum', models.DateField(blank=True, null=True, verbose_name='Fälligkeitsdatum')),
                ('kostenstelle', models.CharField(blank=True, max_length=100, verbose_name='Kostenstelle')),
                ('kategorie', models.CharField(blank=True, max_length=100, verbose_name='Kategorie')),
                ('bemerkung', models.TextField(blank=True, verbose_name='Bemerkung')),
                ('status', models.CharField(choices=[('Offen', 'Offen'), ('In Bearbeitung', 'In Bearbeitung'), ('Erledigt', 'Erledigt')], default='Offen', max_length=30, verbose_name='Status')),
                ('bezahlt_am', models.DateField(blank=True, null=True, verbose_name='Bezahlt am')),
                ('zahlungsreferenz', models.CharField(blank=True, max_length=200, verbose_name='Zahlungsreferenz')),
                ('rechnung_datei', models.FileField(blank=True, null=True, upload_to='rechnungen/', verbose_name='Rechnung')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_rechnungen', to=settings.AUTH_USER_MODEL)),
                ('verantwortlicher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verantwortliche_rechnungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
