# Generated by Django 6.0.7 on 2026-08-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0034_rechnung'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechnung',
            name='lieferschein_datei',
            field=models.FileField(blank=True, null=True, upload_to='lieferscheine/', verbose_name='Lieferschein'),
        ),
    ]
