# Generated by Django 6.0.7 on 2026-08-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0035_rechnung_lieferschein_datei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechnung',
            name='verantwortlicher',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Verantwortlicher'),
        ),
    ]
