# Generated by Django 6.0.7 on 2026-08-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0036_alter_rechnung_verantwortlicher'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechnungKategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rechnung Kategorie',
                'verbose_name_plural': 'Rechnung Kategorien',
                'ordering': ['name'],
            },
        ),
    ]
