# Generated by Django 6.0.7 on 2026-08-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0037_rechnungkategorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rechnung',
            options={'ordering': ['-erstellt_am'], 'permissions': [('access_rechnung', 'Can access Rechnung')], 'verbose_name': 'Rechnung', 'verbose_name_plural': 'Rechnungen'},
        ),
    ]
