# Generated by Django 6.0.7 on 2026-08-21 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0038_alter_rechnung_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.BooleanField(default=True)),
                ('dashboard', models.BooleanField(default=True)),
                ('geraete_neu', models.BooleanField(default=True)),
                ('geraete_gesamt', models.BooleanField(default=True)),
                ('reparatur_melden', models.BooleanField(default=True)),
                ('reparatur_uebersicht', models.BooleanField(default=True)),
                ('reparatur_historie', models.BooleanField(default=True)),
                ('filterwechsel_neu', models.BooleanField(default=True)),
                ('filterwechsel_historie', models.BooleanField(default=True)),
                ('wartung', models.BooleanField(default=True)),
                ('medizingeraete_dokumente', models.BooleanField(default=True)),
                ('techniker_dokumente', models.BooleanField(default=True)),
                ('rechnung_neu', models.BooleanField(default=True)),
                ('rechnung_uebersicht', models.BooleanField(default=True)),
                ('rechnung_historie', models.BooleanField(default=True)),
                ('firma_neu', models.BooleanField(default=True)),
                ('firmeninformationen', models.BooleanField(default=True)),
                ('kontakt', models.BooleanField(default=True)),
                ('einstellungen', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
