# Generated by Django 6.0.7 on 2026-08-24 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0040_remove_userpermission_dashboard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicepruefung',
            name='pruefart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geraete_pruefungen', to='devices.pruefart'),
        ),
    ]
