# Generated by Django 6.0.7 on 2026-08-24 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0041_alter_devicepruefung_pruefart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.documenttype', verbose_name='Dokumenttyp'),
        ),
    ]
