# Generated by Django 6.0.7 on 2026-08-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0042_alter_devicedocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='inventory_number',
            field=models.CharField(max_length=100, verbose_name='Inventarnummer'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Aktiv')), fields=('inventory_number',), name='unique_active_inventory_number'),
        ),
    ]
