# Generated by Django 6.0.7 on 2026-08-26 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0043_alter_device_inventory_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechnung',
            name='kategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechnungen', to='devices.rechnungkategorie', verbose_name='Kategorie'),
        ),
    ]
