# Generated by Django 6.0.7 on 2026-08-26 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0044_alter_rechnung_kategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='pruef_status',
            field=models.CharField(blank=True, choices=[('gueltig', '🟢 Gültig'), ('faellig', '🟡 Fällig'), ('ueberfaellig', '🔴 Überfällig')], max_length=20, null=True, verbose_name='Prüfungsstatus'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='pruefart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.pruefart', verbose_name='Prüfungsart'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='rechnung_status',
            field=models.CharField(blank=True, choices=[('Offen', '🔵 Offen'), ('In Bearbeitung', '🟡 In Bearbeitung'), ('Erledigt', '🟢 Erledigt')], max_length=30, null=True, verbose_name='Rechnungsstatus'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(choices=[('devices_overview', 'Geräteübersicht'), ('devices', 'Geräte'), ('repairs_open', 'Offene Reparaturen'), ('repairs_progress', 'Reparaturen in Bearbeitung'), ('repairs_done', 'Reparaturen erledigt'), ('repair_history', 'Reparaturhistorie'), ('filter_history', 'Filterwechselhistorie'), ('pruefart', 'Prüfungsart'), ('rechnung', 'Rechnungen'), ('device_documents', 'Medizingeräte Dokumente'), ('technician_documents', 'Technikerdokumente')], max_length=50),
        ),
    ]
