# Generated by Django 6.0.7 on 2026-08-26 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0045_dashboardwidget_pruef_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='reparatur_status',
            field=models.CharField(blank=True, choices=[('offen', '🔵 Offen'), ('in_bearbeitung', '🟡 In Bearbeitung'), ('erledigt', '🟢 Erledigt')], max_length=30, null=True, verbose_name='Reparaturstatus'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='geraetart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.geraetart', verbose_name='Geräteart'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='rechnung_status',
            field=models.CharField(blank=True, choices=[('offen', '🔵 Offen'), ('in_bearbeitung', '🟡 In Bearbeitung'), ('erledigt', '🟢 Erledigt')], max_length=30, null=True, verbose_name='Rechnungsstatus'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='standort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.standort', verbose_name='Standort'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(choices=[('devices_overview', 'Geräteübersicht'), ('devices', 'Geräte'), ('repairs_open', 'Reparaturen'), ('repair_history', 'Reparaturhistorie'), ('filter_history', 'Filterwechselhistorie'), ('pruefart', 'Prüfungsart'), ('rechnung', 'Rechnungen'), ('device_documents', 'Medizingeräte Dokumente'), ('technician_documents', 'Technikerdokumente')], max_length=50),
        ),
    ]
