# Generated by Django 6.0.7 on 2026-08-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0046_dashboardwidget_reparatur_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='icon',
            field=models.CharField(choices=[('bi-grid', '📊 Übersicht'), ('bi-hospital', '🏥 Krankenhaus'), ('bi-tools', '🛠 Reparaturen'), ('bi-filter', '🧪 Filterwechsel'), ('bi-calendar-check', '📅 Prüfungen'), ('bi-file-earmark-text', '📄 Rechnungen'), ('bi-heart-pulse', '❤️ Medizin'), ('bi-folder', '📁 Dokumente'), ('bi-gear', '⚙ Einstellungen')], default='bi-grid', max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(choices=[('devices_overview', 'Geräteübersicht'), ('devices', 'Geräte'), ('repairs', 'Reparaturen'), ('filter_history', 'Filterwechselhistorie'), ('pruefart', 'Prüfungsart'), ('rechnung', 'Rechnungen'), ('device_documents', 'Medizingeräte Dokumente'), ('technician_documents', 'Technikerdokumente')], max_length=50),
        ),
    ]
