# Generated by Django 6.0.7 on 2026-08-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0048_dashboardwidget_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messmittel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Messmittel')),
                ('aktiv', models.BooleanField(default=True)),
            ],
        ),
    ]
