# Generated by Django 6.0.7 on 2026-08-28 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0049_messmittel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparatur',
            name='messmittel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.messmittel', verbose_name='Messmittel'),
        ),
    ]
