# Generated by Django 6.0.7 on 2026-08-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0050_reparatur_messmittel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparatur',
            name='elektrische_pruefung',
            field=models.BooleanField(default=False, verbose_name='Elektrische Prüfung'),
        ),
    ]
