# Generated by Django 6.0.7 on 2026-08-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0051_reparatur_elektrische_pruefung'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparatur',
            name='elektrische_pruefung_art',
            field=models.CharField(blank=True, choices=[('Betten', 'Betten'), ('Maschinen', 'Maschinen')], max_length=20, verbose_name='Art der elektrischen Prüfung'),
        ),
    ]
