# Generated by Django 6.0.7 on 2026-08-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0052_reparatur_elektrische_pruefung_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparatur',
            name='elektrische_pruefung_daten',
            field=models.JSONField(blank=True, default=dict, verbose_name='Daten der elektrischen Prüfung'),
        ),
    ]
