# Generated by Django 6.0.7 on 2026-08-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0053_reparatur_elektrische_pruefung_daten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparatur',
            name='messmittel',
        ),
        migrations.AddField(
            model_name='reparatur',
            name='messmittel',
            field=models.ManyToManyField(blank=True, to='devices.messmittel', verbose_name='Messmittel'),
        ),
    ]
