# Generated by Django 6.0.7 on 2026-09-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0054_remove_reparatur_messmittel_reparatur_messmittel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='permission_einstellung_audit_log',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission_einstellung_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission_einstellung_benutzer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission_einstellung_dashboard_widgets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission_einstellung_dokumenttypen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission_einstellung_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission_einstellung_geraetarten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission_einstellung_geraetedetails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission_einstellung_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission_einstellung_kontakt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission_einstellung_messmittel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission_einstellung_pruefarten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission_einstellung_rechnung_kategorien',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission_einstellung_standorte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission_einstellung_system_update',
            field=models.BooleanField(default=False),
        ),
    ]
