# Generated by Django 6.0.7 on 2026-09-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0055_userpermission_permission_einstellung_audit_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='permission_einstellung_benutzer_level',
            field=models.CharField(choices=[('lesen', 'Nur Lesen'), ('admin', 'Wie Admin')], default='lesen', max_length=20),
        ),
    ]
