# Generated by Django 6.0.7 on 2026-09-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0056_userpermission_permission_einstellung_benutzer_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='permission_einstellung_benutzer_level',
        ),
    ]
